import { Fragment } from "react";
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, Textarea } from "./ui";
import { COMPARATOR_OPTIONS, SPEC_OPTIONS } from "../data/constants";
import { primaryStatForSpec } from "../utils/lootLogic";

export default function StickyControlsPanel({ defaultItemCount, manualItemCount, overrideCount, rosterCount, showRoster, onToggleRoster, showManualItems, onToggleManualItems, showSpecOverrides, onToggleSpecOverrides, manualItemsText, onManualItemsTextChange, classOptions, specOptionsForClass, selectedClass, onSelectedClassChange, selectedSpecName, onSelectedSpecChange, selectedSpec, specOverrides, draftOverride, onUpdateSelectedSpec, onApplySelectedSpecOverride, onResetSelectedSpec, onResetAllSpecs, onExportSpecOverrides, onImportSpecOverridesClick, importOverridesInputRef, onImportSpecOverridesFromFile }) {
  return <div className="space-y-6 bg-zinc-950/95 py-4 backdrop-blur supports-[backdrop-filter]:bg-zinc-950/80">
    <Card className="bg-zinc-900 border-zinc-800 shadow-2xl"><CardContent className="pt-6"><div className="flex flex-wrap items-center gap-3 text-sm text-zinc-300">
      <Badge variant="secondary" className="bg-zinc-800 text-zinc-100 border border-zinc-700">Default loot items: {defaultItemCount}</Badge><Badge variant="secondary" className="bg-zinc-800 text-zinc-100 border border-zinc-700">Manual additions: {manualItemCount}</Badge><Badge variant="secondary" className="bg-zinc-800 text-zinc-100 border border-zinc-700">Spec overrides: {overrideCount}</Badge><Badge variant="secondary" className="bg-zinc-800 text-zinc-100 border border-zinc-700">Roster: {rosterCount}</Badge>
      <div className="ml-auto flex flex-wrap items-center gap-3"><Button variant="secondary" className="bg-zinc-800 text-zinc-100 hover:bg-zinc-700" onClick={onToggleRoster}>{showRoster ? "Hide" : "Show"} Roster</Button><Button variant="secondary" className="bg-zinc-800 text-zinc-100 hover:bg-zinc-700" onClick={onToggleManualItems}>{showManualItems ? "Hide" : "Show"} Manual Item Input</Button><Button variant="secondary" className="bg-zinc-800 text-zinc-100 hover:bg-zinc-700" onClick={onToggleSpecOverrides}>{showSpecOverrides ? "Hide" : "Show"} Spec Overrides</Button></div>
    </div></CardContent></Card>
    {showManualItems && <Card className="bg-zinc-900 border-zinc-800 shadow-2xl"><CardHeader><CardTitle className="text-zinc-50">Manual Item Input</CardTitle></CardHeader><CardContent><p className="text-sm text-zinc-300 mb-3">Optional. Add extra comma-separated items here. Format: <span className="text-zinc-100 font-mono">Name, Slot, Type, Stat1, Stat2</span> or <span className="text-zinc-100 font-mono">Name, Slot, Type, Primary, Stat1, Stat2</span></p><Textarea value={manualItemsText} onChange={(e) => onManualItemsTextChange(e.target.value)} className="min-h-[180px] bg-black text-zinc-100 border-zinc-700 font-mono text-sm leading-6" /></CardContent></Card>}
    {showSpecOverrides && <Card className="bg-zinc-900 border-zinc-800 shadow-2xl"><CardHeader><CardTitle className="text-zinc-50">Spec Overrides</CardTitle></CardHeader><CardContent><p className="text-sm text-zinc-300 mb-4">Override the default priority for any spec.</p><div className="grid grid-cols-1 xl:grid-cols-[280px,1fr] gap-4"><div className="grid grid-cols-2 gap-2"><select value={selectedClass} onChange={(e) => onSelectedClassChange(e.target.value)} className="rounded-xl border border-zinc-700 bg-black px-3 py-2">{classOptions.map(c=><option key={c}>{c}</option>)}</select><select value={selectedSpecName} onChange={(e) => onSelectedSpecChange(e.target.value)} className="rounded-xl border border-zinc-700 bg-black px-3 py-2">{specOptionsForClass.map(s=><option key={s}>{s}</option>)}</select></div><div className="space-y-4"><div className="grid grid-cols-2 xl:grid-cols-7 gap-2 items-end">{[0,1,2,3].map(i=><Fragment key={i}><select value={draftOverride.stats[i]} onChange={(e)=>onUpdateSelectedSpec("stats",i,e.target.value)} className="rounded-xl border border-zinc-700 bg-black px-3 py-2">{SPEC_OPTIONS.map(s=><option key={s}>{s}</option>)}</select>{i<3&&<select value={draftOverride.comps[i]} onChange={(e)=>onUpdateSelectedSpec("comps",i,e.target.value)} className="rounded-xl border border-zinc-700 bg-black px-3 py-2">{COMPARATOR_OPTIONS.map(c=><option key={c}>{c}</option>)}</select>}</Fragment>)}</div><div className="flex flex-wrap gap-2"><Button onClick={onApplySelectedSpecOverride}>Apply override</Button><Button variant="secondary" onClick={onResetSelectedSpec}>Reset selected</Button><Button variant="secondary" onClick={onResetAllSpecs}>Reset all</Button><Button variant="secondary" onClick={onExportSpecOverrides}>Export JSON</Button><Button variant="secondary" onClick={onImportSpecOverridesClick}>Import JSON</Button><input ref={importOverridesInputRef} type="file" accept="application/json,.json" className="hidden" onChange={onImportSpecOverridesFromFile}/></div><div className="rounded-xl border border-zinc-800 bg-black px-3 py-3 text-sm text-zinc-300">Effective priority: <span className="text-zinc-100 font-mono">{selectedSpec} {primaryStatForSpec(selectedSpec)} &gt;&gt; {draftOverride.stats.join(" ")}</span> {specOverrides[selectedSpec] ? "(custom)" : "(default)"}</div></div></div></CardContent></Card>}
  </div>;
}
